FROM openeuler/openeuler:20.03-lts-sp3
ARG _UID=6213
ARG _GID=11429
ARG _LOGIN=swx-jenkins
ARG _HOME=/var/home/$_LOGIN
ARG MOFED_VER
ENV LANG=en_US.utf-8
USER root

# Default openeuleros repos are unstable and very slow, so replace
# them with internal webrepo
RUN set -eux; \
    sed -i 's/enabled=1/enabled=0/' /etc/yum.repos.d/openEuler.repo && \
    echo -e "[1_base]\n\
name=1_base\n\
baseurl=http://webrepo.mtl.labs.mlnx/openEuler/20.03.3/\$basearch/\n\
enabled=1\n\
gpgcheck=0" > /etc/yum.repos.d/1_base.repo

RUN yum install -y ca-certificates

RUN yum install -y \
    sudo \
    git \
    wget \
    fakeroot \
    ncurses-devel \
    rpm-build doxygen \
    graphviz \
    numactl-devel \
    libiscsi-devel \
    make \
    gcc \
    CUnit-devel \
    libaio-devel \
    openssl-devel \
    libuuid-devel \
    gcc-c++ \
    python3 \
    meson \
    python3-pip \
    python3-configshell \
    bc \
    pkgconfig autoconf automake libtool

RUN set -eux; \
    echo -e "[mlnx_ofed]\n\
name=Mellanox Technologies \$basearch mlnx_ofed\n\
baseurl=http://webrepo.mtr.labs.mlnx/mswg/release/MLNX_OFED/MLNX_OFED_LINUX-${MOFED_VER}/MLNX_OFED_LINUX-${MOFED_VER}-openeuler20.03sp3-\$basearch/RPMS/\n\
enabled=1\n\
gpgcheck=0" > /etc/yum.repos.d/mellanox_mlnx_ofed.repo; \
    dnf install -y mlnx-ofed-basic-user-only 

RUN pip3 install --prefix=/usr/ pyelftools

RUN echo "${_LOGIN} ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
RUN mkdir -p $_HOME
RUN groupadd -f -g "$_GID" "$_LOGIN"
RUN useradd -u "$_UID" -g "$_GID" -s /bin/bash -m -d ${_HOME} "$_LOGIN"
RUN chown $_LOGIN $_HOME
RUN yum clean all

SHELL ["/bin/bash"]
USER "${_LOGIN}"
ENTRYPOINT [ "/bin/bash", "--login", "--rcfile", "/etc/bashrc", "-c" ]
