#  SPDX-License-Identifier: BSD-3-Clause
#  Copyright (c) 2023-2024 NVIDIA CORPORATION & AFFILIATES.
#  All rights reserved.
#

SPDK_ROOT_DIR := $(abspath $(CURDIR)/../../../../..)
include $(SPDK_ROOT_DIR)/mk/spdk.common.mk
TEST_FILE = rdma_utils_ut.c

include $(SPDK_ROOT_DIR)/mk/spdk.unittest.mk
